org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3 
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
loader_version=0.16.10

# Mod Properties
maven_group=net.shiroha233.roadweaver

# Dependencies
fabric_version=0.138.3+1.21.10
neoforge_version=21.10.64
architectury_version=18.0.8
cloth_config_version=20.0.149
c2me_fabric_version=0.3.6+alpha.0.9+1.21.10
c2me_neoforge_version=0.3.6+alpha.0.78+1.21.10
modmenu_version=15.0.0
placeholder_api_version=2.7.2+1.21.8