# 负责项目版本、依赖版本与默认运行参数配置。
org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3 
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.16.14

# Mod Properties
maven_group=net.shiroha233.roadweaver

# Dependencies
fabric_version=0.141.3+1.21.11
neoforge_version=21.11.38-beta
architectury_version=19.0.1
cloth_config_version=21.11.153
dynamictrees_version=1.5.0-BETA07
modmenu_version=17.0.0-beta.2

# 运行游戏时的人物名称
minecraft_username=YourName

# Java toolchains
runtime_java_version=21

# Fabric 开发环境可选依赖
fabric_enable_modmenu=false
