pluginManagement {
	repositories {
		maven {
			name = 'LocalMaven'
			url = uri("${rootDir}/gradle/local-maven")
		}
		gradlePluginPortal()
		maven {
			name = 'Architectury'
			url = 'https://maven.architectury.dev/'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
	}
}

dependencyResolutionManagement {
	repositories {
		maven {
			name = 'LocalMaven'
			url = uri("${rootDir}/gradle/local-maven")
		}
		mavenCentral()
		maven { url = 'https://maven.fabricmc.net/' }
		maven { url = 'https://maven.architectury.dev/' }
		maven { url = 'https://maven.shedaniel.me/' }
		maven { url = 'https://maven.terraformersmc.com/' }
		maven { url = 'https://api.modrinth.com/maven' }
	}
}

rootProject.name = 'roadweaver'
include 'common'
include 'fabric'
