{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoform",
    "version": "1.21.11-20251209.172050",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "neoformData",
      "attributes": {
        "org.gradle.jvm.version": 21
      },
      "dependencies": [
        {
          "group": "org.vineflower",
          "module": "vineflower",
          "version": {
            "requires": "1.11.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "fatjar"
            }
          }
        },
        {
          "group": "net.neoforged",
          "module": "AutoRenamingTool",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "AutoRenamingTool",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "installertools",
          "version": {
            "requires": "4.0.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "installertools",
              "type": "jar",
              "extension": "jar",
              "classifier": "fatjar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "neoform-1.21.11-20251209.172050.zip",
          "url": "neoform-1.21.11-20251209.172050.zip",
          "size": 1026216,
          "sha512": "102f9484df77abe255f82e13a95cf927ecc97288ed5d27d67623493d9dc93b1522d0e30eb72cb45a90f5b8aacb17db4361632599102d31e813efe5adaaee98a1",
          "sha256": "9e6fbc58fb36a2217ae23ec6f2d36a043a30e8a2878a5b77de9f41e92d04385f",
          "sha1": "d212f433d03621c297379f042a83e1078817aa5c",
          "md5": "86f1106916996df0a88278822e066416"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform",
          "version": "1.21.11-20251209.172050"
        }
      ]
    },
    {
      "name": "neoformRuntimeElements",
      "attributes": {
        "org.gradle.jvm.version": 21,
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "minecraft-dependencies",
          "version": {
            "requires": "1.21.11"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform-dependencies",
          "version": "1.21.11-20251209.172050"
        }
      ]
    },
    {
      "name": "neoformApiElements",
      "attributes": {
        "org.gradle.jvm.version": 21,
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ca.weblite",
          "module": "java-objc-bridge",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "net.neoforged",
          "module": "minecraft-dependencies",
          "version": {
            "requires": "1.21.11"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform-dependencies",
          "version": "1.21.11-20251209.172050"
        }
      ]
    },
    {
      "name": "parameterMappings",
      "attributes": {
        "net.neoforged.symbol-mappings-format": "tsrg2-lzma",
        "org.gradle.category": "data",
        "org.gradle.usage": "symbol-mappings"
      },
      "files": [
        {
          "name": "neoform-1.21.11-20251209.172050-mappings.tsrg.lzma",
          "url": "neoform-1.21.11-20251209.172050-mappings.tsrg.lzma",
          "size": 557177,
          "sha512": "3174cf1cbb0d3445967237584b2465b6c77306ec649d0396b5be2e26745998c533e6edd34c2e25982519e6e0f7b57580d47da251aad1c2f8c4a175f035a8254c",
          "sha256": "fca8bf09ca43e18d5c9b0baab5aabbfb7b755541e5b48f5bf2df44c558915758",
          "sha1": "d781f508b150f03bd379da48fb9ce0c1c227e87d",
          "md5": "411583f0c6d244f0b1e2199e12acac94"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform-parameter-mappings",
          "version": "1.21.11-20251209.172050"
        }
      ]
    }
  ]
}
