package net.shiroha233.roadweaver.features.path.decoration.material;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Holder;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.WorldGenLevel;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.Biomes;
import net.minecraft.tags.BiomeTags;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Resolves a small, deterministic road palette from the biome and the terrain
 * immediately around the road. Custom biome/worldgen mods are supported without
 * hard dependencies by using the active terrain blocks as palette candidates.
 */
public final class BiomeRoadMaterialSelector {
    private static final Map<ResourceKey<Biome>, List<BlockState>> PALETTE_CACHE = new ConcurrentHashMap<>();

    private BiomeRoadMaterialSelector() {}

    public static List<BlockState> forBiome(WorldGenLevel world, BlockPos pos) {
        Holder<Biome> biome = world.getBiome(pos);
        Optional<ResourceKey<Biome>> keyOpt = biome.unwrapKey();
        if (keyOpt.isEmpty()) {
            return vanillaFallback(biome, world, pos);
        }

        ResourceKey<Biome> key = keyOpt.get();
        List<BlockState> cached = PALETTE_CACHE.get(key);
        if (cached != null) {
            return cached;
        }

        List<BlockState> resolved = buildPalette(biome, world, pos);
        List<BlockState> previous = PALETTE_CACHE.putIfAbsent(key, resolved);
        return previous != null ? previous : resolved;
    }

    private static List<BlockState> buildPalette(Holder<Biome> biome, WorldGenLevel world, BlockPos pos) {
        LinkedHashSet<Block> blocks = new LinkedHashSet<>();

        // Prefer blocks actually generated by the active worldgen stack. This is
        // the compatibility path for modded biomes without hard dependencies.
        addTerrainBlock(blocks, world.getBlockState(pos.below()).getBlock());
        addTerrainBlock(blocks, world.getBlockState(pos.below(2)).getBlock());
        addTerrainBlock(blocks, world.getBlockState(pos.below(3)).getBlock());
        addTerrainBlock(blocks, world.getBlockState(pos.west()).getBlock());
        addTerrainBlock(blocks, world.getBlockState(pos.east()).getBlock());

        addBiomeDefaults(blocks, biome);

        List<BlockState> result = new ArrayList<>(4);
        for (Block block : blocks) {
            result.add(block.defaultBlockState());
            if (result.size() >= 4) break;
        }

        if (result.isEmpty()) {
            result.add(Blocks.DIRT_PATH.defaultBlockState());
            result.add(Blocks.GRAVEL.defaultBlockState());
        }
        return Collections.unmodifiableList(result);
    }

    private static List<BlockState> vanillaFallback(Holder<Biome> biome, WorldGenLevel world, BlockPos pos) {
        LinkedHashSet<Block> blocks = new LinkedHashSet<>();
        addTerrainBlock(blocks, world.getBlockState(pos.below()).getBlock());
        addTerrainBlock(blocks, world.getBlockState(pos.below(2)).getBlock());
        addBiomeDefaults(blocks, biome);
        List<BlockState> result = new ArrayList<>(4);
        for (Block block : blocks) {
            result.add(block.defaultBlockState());
            if (result.size() >= 4) break;
        }
        return Collections.unmodifiableList(result);
    }

    private static void addTerrainBlock(LinkedHashSet<Block> blocks, Block block) {
        // Avoid vegetation, fluids and blocks that should never become road fill.
        if (block == Blocks.AIR || block == Blocks.CAVE_AIR || block == Blocks.VOID_AIR
                || block == Blocks.WATER || block == Blocks.LAVA
                || block == Blocks.TALL_GRASS || block == Blocks.GRASS
                || block == Blocks.FERN || block == Blocks.LARGE_FERN
                || block == Blocks.DEAD_BUSH || block == Blocks.SUGAR_CANE
                || block == Blocks.SWEET_BERRY_BUSH || block == Blocks.VINE
                || block == Blocks.GLOW_LICHEN || block == Blocks.MOSS_CARPET
                || block == Blocks.SNOW || block == Blocks.SNOW_BLOCK
                || block == Blocks.MANGROVE_ROOTS) {
            return;
        }
        blocks.add(block);
    }

    private static void addBiomeDefaults(LinkedHashSet<Block> blocks, Holder<Biome> biome) {
        Optional<ResourceKey<Biome>> keyOpt = biome.unwrapKey();
        if (keyOpt.isPresent()) {
            ResourceKey<Biome> key = keyOpt.get();
            if (key == Biomes.DESERT || key == Biomes.BEACH) {
                blocks.add(Blocks.SANDSTONE);
                blocks.add(Blocks.CUT_SANDSTONE);
                blocks.add(Blocks.SAND);
            } else if (key == Biomes.BADLANDS || key == Biomes.ERODED_BADLANDS || key == Biomes.WOODED_BADLANDS) {
                blocks.add(Blocks.RED_SANDSTONE);
                blocks.add(Blocks.CUT_RED_SANDSTONE);
                blocks.add(Blocks.TERRACOTTA);
            } else if (biome.is(BiomeTags.IS_SAVANNA)) {
                blocks.add(Blocks.COARSE_DIRT);
                blocks.add(Blocks.DIRT_PATH);
                blocks.add(Blocks.GRAVEL);
            } else if (biome.is(BiomeTags.IS_JUNGLE) || key == Biomes.BAMBOO_JUNGLE) {
                blocks.add(Blocks.MOSSY_COBBLESTONE);
                blocks.add(Blocks.DIRT_PATH);
                blocks.add(Blocks.COARSE_DIRT);
            } else if (biome.is(BiomeTags.IS_TAIGA)) {
                blocks.add(Blocks.COARSE_DIRT);
                blocks.add(Blocks.GRAVEL);
                blocks.add(Blocks.PODZOL);
            } else if (key == Biomes.SNOWY_PLAINS || key == Biomes.SNOWY_TAIGA || key == Biomes.GROVE
                    || key == Biomes.SNOWY_SLOPES || key == Biomes.JAGGED_PEAKS || key == Biomes.FROZEN_PEAKS) {
                blocks.add(Blocks.ANDESITE);
                blocks.add(Blocks.COBBLESTONE);
                blocks.add(Blocks.GRAVEL);
            } else if (key == Biomes.SWAMP || key == Biomes.MANGROVE_SWAMP) {
                blocks.add(Blocks.PACKED_MUD);
                blocks.add(Blocks.MUD);
                blocks.add(Blocks.COARSE_DIRT);
            } else if (key == Biomes.DARK_FOREST) {
                blocks.add(Blocks.MOSSY_COBBLESTONE);
                blocks.add(Blocks.COBBLESTONE);
                blocks.add(Blocks.DIRT_PATH);
            } else if (key == Biomes.BIRCH_FOREST || key == Biomes.OLD_GROWTH_BIRCH_FOREST || key == Biomes.CHERRY_GROVE) {
                blocks.add(Blocks.DIRT_PATH);
                blocks.add(Blocks.GRAVEL);
                blocks.add(Blocks.COBBLESTONE);
            } else if (key == Biomes.STONY_PEAKS || key == Biomes.WINDSWEPT_FOREST || key == Biomes.WINDSWEPT_HILLS
                    || key == Biomes.WINDSWEPT_GRAVELLY_HILLS) {
                blocks.add(Blocks.STONE);
                blocks.add(Blocks.COBBLESTONE);
                blocks.add(Blocks.GRAVEL);
            } else if (key == Biomes.MUSHROOM_FIELDS) {
                blocks.add(Blocks.STONE);
                blocks.add(Blocks.COBBLESTONE);
            }
        }

        if (blocks.isEmpty()) {
            blocks.add(Blocks.DIRT_PATH);
            blocks.add(Blocks.GRAVEL);
            blocks.add(Blocks.COARSE_DIRT);
        }
    }
}
