modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "roadweaver"
version = "${mod_version}"
displayName = "RoadWeaver"
authors = "shiroha233"
credits = "Includes code adapted from 'settlement-roads-new' (CC0-1.0) by Countered."
description = '''Automatically generates roads between structures like villages.'''
logoFile = "assets/roadweaver/icon.png"

[[dependencies.roadweaver]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadweaver]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadweaver]]
modId = "architectury"
type = "required"
versionRange = "[21.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.roadweaver]]
modId = "cloth_config"
type = "optional"
versionRange = "[26.2.155,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "roadweaver.mixins.json"
