modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "roadweaver"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"
    description = "${mod_description}"

[[mixins]]
    config = "roadweaver.mixins.json"

[[dependencies.roadweaver]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.roadweaver]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "BOTH"
