/* 文件职责：承载初始生成各阶段供客户端只读展示的进度快照。 */
package net.shiroha233.roadweaver.generation.progress;

/**
 * 初始生成进度快照，供客户端加载界面只读展示。
 */
public record InitialGenerationProgressSnapshot(
        boolean active,
        InitialGenerationStage stage,
        String stageLabel,
        long startedAtMillis,
        long elapsedMillis,
        int overallPercent,
        int stagePercent,
        int connectionsTotal,
        int connectionsGenerating,
        int connectionsDone,
        int connectionsFailed,
        int tilesTotal,
        int tilesLoaded,
        int tilesSampled,
        int tilesFromMemory,
        int tilesFromDisk,
        long samplesTotal,
        long samplesDone,
        int exactPathsTotal,
        int exactPathsDone,
        double samplesPerSecond,
        int lastBatchSamples,
        long lastBatchMillis,
        String backend,
        String deviceName,
        String devicePreference,
        String fallbackReason,
        int initialThreads,
        int activeWorkers,
        String currentOperation,
        int terrainCacheHitPercent,
        long terrainNoiseSamplesTotal,
        double terrainNoiseSamplesPerSec,
        int accurateCacheHitPercent,
        long accurateBaseHeightTotal,
        double accurateBaseHeightPerSec
) {
    public static InitialGenerationProgressSnapshot inactive() {
        return new InitialGenerationProgressSnapshot(
                false,
                InitialGenerationStage.FINISHED,
                InitialGenerationStage.FINISHED.labelKey(),
                0L,
                0L,
                100,
                100,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0L,
                0L,
                0,
                0,
                0.0,
                0,
                0L,
                "-",
                "-",
                "-",
                "",
                0,
                0,
                "",
                0,
                0L,
                0.0,
                0,
                0L,
                0.0
        );
    }
}
